# Change these first
owner: gatestatus # Your GitHub organization or username, where this repository lives
repo: txms # The name of this repository

sites:
  - name: DataLayer - Core Devin
    url: $PING_DATALAYER_DEVIN_1
    icon: https://raw.githubusercontent.com/gatestatus/txms/master/assets/providers/datalayer.png
    maxResponseTime: 7000
    expectedStatusCodes:
      - 200
    assignees:
      - rastislavcore
  - name: DataLayer - Core Mainnet
    url: $PING_DATALAYER_MAINNET_1
    icon: https://raw.githubusercontent.com/gatestatus/txms/master/assets/providers/datalayer.png
    maxResponseTime: 7000
    expectedStatusCodes:
      - 200
    assignees:
      - rastislavcore

commitMessages:
  commitAuthorName: "Txms Bot"
  commitAuthorEmail: "bot@txms.info"

skipDescriptionUpdate: true
skipTopicsUpdate: true
skipHomepageUpdate: true

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: txms.info
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/gatestatus/txms/master/assets/logo/txms.svg
  name: TXMS Status
  introTitle: "**TXMS Status** is the monitoring service for TXMS providers."
  introMessage: You can choose a provider for your region and stable uptime to deliver your messages.
  favicon: https://raw.githubusercontent.com/gatestatus/txms/master/assets/icons/txms.png
  faviconSvg: https://raw.githubusercontent.com/gatestatus/txms/master/assets/icons/txms.svg
  customHeadHtml: "<meta property='wallet:xcb' content='cb7147879011ea207df5b35a24ca6f0859dcfb145999'>"
  navbar:
    - title: TXMS
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

i18n:
  footer: This page is [open source]($REPO), observing [TXMS Services](https://github.com/cryptohub-digital/txms.js)
