# Change these first
owner: gatestatus # Your GitHub organization or username, where this repository lives
repo: txms # The name of this repository

sites:
  - name: DataLayer - Core Devin
    url: $PING_DATALAYER_DEVIN_1
    icon: https://raw.githubusercontent.com/gatestatus/txms/master/assets/providers/datalayer.png
    maxResponseTime: 7000
    expectedStatusCodes:
      - 200
    assignees:
      - rastislavcore
  - name: DataLayer - Core Mainnet
    url: $PING_DATALAYER_MAINNET_1
    icon: https://raw.githubusercontent.com/gatestatus/txms/master/assets/providers/datalayer.png
    maxResponseTime: 7000
    expectedStatusCodes:
      - 200
    assignees:
      - rastislavcore

commitMessages:
  commitAuthorName: "Txms Bot"
  commitAuthorEmail: "bot@txms.info"

skipDescriptionUpdate: true
skipTopicsUpdate: true
skipHomepageUpdate: true

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: txms.info
  # baseUrl: /your-repo-name
  logoUrl: https://corecdn.info/badge/svg/32/txms.svg
  name: TXMS Status
  introTitle: "**TXMS Status** is an observation tool for entities participating in the TXMS ecosystem."
  introMessage:
    |
    You are empowered to decide on a provider based on your region, ensuring a steady uptime for reliable message conveyance.

    Here's the detail for Core Mainnet:

    | Region | Number |
    |--------|--------|
    | Global | +12019715152 |
    | US | +12019715152 |

    And for the Core Testnet (Devín):

    | Region | Number |
    |--------|--------|
    | Global | +12014835939 |
    | US | +12014835939 |
  favicon: https://corecdn.info/mark/png/32/txms.png
  faviconSvg: https://corecdn.info/mark/svg/32/txms.svg
  customHeadHtml: "<meta property='ican:xcb' content='cb7147879011ea207df5b35a24ca6f0859dcfb145999' />"
  navbar:
    - title: TXMS
      href: https://github.com/cryptohub-digital/txms.js
    - title: "CRYPTO ▪ HUB"
      href: https://github.com/cryptohub-digital

i18n:
  footer: This page is [open source]($REPO), observing [TXMS Services](https://github.com/cryptohub-digital/txms.js)
