blank_issues_enabled: false
contact_links:
  - name: Readme
    url: https://github.com/gatestatus/txms#readme
    about: Read more about the service
  - name: Module
    url: https://github.com/cryptohub-digital/txms.js#readme
    about: Get information about module
